export class Payroll    {
payrollId: number = 0.0;
employeeId: number = 0;
annualSalary: number = 0.0;
basicPay: number = 0.0;
houseRentalAllowance: number = 0.0;
statuatoryBonus: number = 0.0;
medicalAllowance: number = 0.0;
conveyanceAllowance: number = 0.0;
specialAllowance: number = 0.0;
professionalTax: number = 0.0;
providentFund: number = 0.0;
incomeTax: number = 0.0;
netTakeHome: number = 0.0;
totalEarnings: number = 0.0;
totalDeductions: number = 0.0;
payrollYear: number = 0;
payrollMonth: number = 0;
payrollDay: number = 0;
empName: string = '';
empJobRole: string = '';
empEmail: string = '';
payrollMonthName: string = '';
}